require("lawsonguilbeau.plugins-setup")
require("lawsonguilbeau.core.options")
require("lawsonguilbeau.core.keymaps")
require("lawsonguilbeau.core.colorscheme")
require("lawsonguilbeau.plugins.comment")
require("lawsonguilbeau.plugins.nvim-tree")
require("lawsonguilbeau.plugins.lualine")
require("lawsonguilbeau.plugins.telescope")
require("lawsonguilbeau.plugins.nvim-cmp")
require("lawsonguilbeau.plugins.lsp.mason")
require("lawsonguilbeau.plugins.lsp.lspsaga")
require("lawsonguilbeau.plugins.lsp.lspconfig")
require("lawsonguilbeau.plugins.lsp.null-ls")
require("lawsonguilbeau.plugins.autopairs")
require("lawsonguilbeau.plugins.treesitter")
require("lawsonguilbeau.plugins.gitsigns")
require("lawsonguilbeau.plugins.hbac")
require("neoscroll").setup()

vim.opt.termguicolors = true
require("bufferline").setup({})
