#!/bin/bash

options=(
	style=round
	width=4.0
	hidpi=off
  active_color="gradient(top_left=0xff15BCF9,bottom_right=0xff5FFBC6)"
	inactive_color=0x00414550
  background_color=0x10414550
  blur_radius=24
)

borders "${options[@]}"
